// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ExportAsCurl(arg1:number):Promise<string>;

export function GetRequest(arg1:number):Promise<backend.Request>;

export function GetRequests():Promise<Array<backend.Request>>;

export function ReplayRequest(arg1:number,arg2:string):Promise<void>;

export function SetForwardURL(arg1:string):Promise<void>;

export function StartTunnel():Promise<string>;

export function StopTunnel():Promise<void>;
