// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportAsCurl(arg1) {
  return window['go']['main']['App']['ExportAsCurl'](arg1);
}

export function GetRequest(arg1) {
  return window['go']['main']['App']['GetRequest'](arg1);
}

export function GetRequests() {
  return window['go']['main']['App']['GetRequests']();
}

export function ReplayRequest(arg1, arg2) {
  return window['go']['main']['App']['ReplayRequest'](arg1, arg2);
}

export function SetForwardURL(arg1) {
  return window['go']['main']['App']['SetForwardURL'](arg1);
}

export function StartTunnel() {
  return window['go']['main']['App']['StartTunnel']();
}

export function StopTunnel() {
  return window['go']['main']['App']['StopTunnel']();
}
